//
// An iOS control that makes content scroll vertically.
//
// https://github.com/marketplacer/Scrollable
//
// This file was automatically generated by combining multiple Swift source files.
//


// ----------------------------
//
// Scrollable.swift
//
// ----------------------------

import UIKit

/**
 Makes the content in the scroll view scrollable.
 */
public class Scrollable {
  public class func createContentView(scrollView: UIScrollView) -> UIView {
    let contentView = UIView()
    scrollView.addSubview(contentView)
    Scrollable.embedSubviews(scrollView, inNewSuperview: contentView)
    Scrollable.layoutContentViewInScrollView(contentView, scrollView: scrollView)
    scrollView.layoutIfNeeded()
    
    return contentView
  }
  
  class func layoutContentViewInScrollView(contentView: UIView, scrollView: UIView) {
    // Make content view fill scroll view
    
    ScrollableAutolayoutConstraints.fillParent(contentView, parentView: scrollView, margin: 0,
                                               vertically: false)
    
    ScrollableAutolayoutConstraints.fillParent(contentView, parentView: scrollView, margin: 0,
                                               vertically: true)
    
    // Content view width is equal to scroll view width
    ScrollableAutolayoutConstraints.equalWidth(contentView, viewTwo: scrollView,
                                               constraintContainer: scrollView)
  }
  
  class func embedSubviews(fromView: UIView, inNewSuperview newSuperview: UIView) {
    newSuperview.translatesAutoresizingMaskIntoConstraints = false
    
    // Move all subviews to newSuperview
    for subview in fromView.subviews {
      if subview == newSuperview { continue }
      newSuperview.addSubview(subview)
    }
    
    // Move all scrollview constraints to contentView
    moveConstraints(fromView, toView: newSuperview)
  }
  
  class func moveConstraints(fromView: UIView, toView: UIView) {
    let constraints = fromView.constraints
    for constraint in constraints {
      moveConstraint(constraint, fromView: fromView, toView: toView)
    }
  }
  
  private class func moveConstraint(constraint: NSLayoutConstraint,
                                    fromView: UIView, toView: UIView) {
    
    if let firstItem = constraint.firstItem as? NSObject {
      
      let newFirstItem = firstItem == fromView ? toView : firstItem
      
      if let secondItem = constraint.secondItem as? NSObject {
        let newSecondItem = secondItem == fromView ? toView : secondItem
        
        let newConstraint = NSLayoutConstraint(
          item: newFirstItem,
          attribute: constraint.firstAttribute,
          relatedBy: constraint.relation,
          toItem: newSecondItem,
          attribute: constraint.secondAttribute,
          multiplier: constraint.multiplier,
          constant: constraint.constant
        )
        
        newConstraint.priority = constraint.priority
        
        fromView.removeConstraint(constraint)
        
        toView.addConstraint(newConstraint)
      }
    }
  }
}


// ----------------------------
//
// ScrollableAutolayoutConstraints.swift
//
// ----------------------------

//
//  Collection of shortcuts to create autolayout constraints.
//

import UIKit

class ScrollableAutolayoutConstraints {
  class func fillParent(view: UIView, parentView: UIView, margin: CGFloat = 0, vertically: Bool = false) {
    var marginFormat = ""
    
    if margin != 0 {
      marginFormat = "-\(margin)-"
    }
    
    var format = "|\(marginFormat)[view]\(marginFormat)|"
    
    if vertically {
      format = "V:" + format
    }
    
    let constraints = NSLayoutConstraint.constraintsWithVisualFormat(format,
                                                                     options: [], metrics: nil,
                                                                     views: ["view": view])
    
    parentView.addConstraints(constraints)
  }
  
  class func equalWidth(viewOne: UIView, viewTwo: UIView, constraintContainer: UIView) -> [NSLayoutConstraint] {
    
    let constraints = NSLayoutConstraint.constraintsWithVisualFormat("[viewOne(==viewTwo)]",
                                                                     options: [], metrics: nil,
                                                                     views: ["viewOne": viewOne, "viewTwo": viewTwo])
    
    constraintContainer.addConstraints(constraints)
    
    return constraints
  }
}